In [1]:
import numpy as np

In [2]:
# Crear arreglo
np.array([10,20,30,40,50,60])

array([10, 20, 30, 40, 50, 60])

In [8]:
# Guardar arreglo en una variable
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[4]

5

In [9]:
# Mostrar los datos del arreglo a partir de la posicion 3
a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [11]:
# Mostrar el arreglo con saltos de 2
a[::2]

array([1, 3, 5, 7, 9])

In [16]:
# Crear arreglo y matriz de ceros
print('Array:')
print(np.zeros(5))
print('Matriz:')
print(np.zeros((4,5)))

Array:
[0. 0. 0. 0. 0.]
Matriz:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
# Crear arreglo y matriz de unos
print('Array:')
print(np.ones(5))
print('Matriz:')
print(np.ones((4,5)))

Array:
[1. 1. 1. 1. 1.]
Matriz:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
# Crear arreglo (primer valor, ultimo valor, total de elementos)
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [21]:
b = np.array([['x', 'y', 'z'], ['a', 'c', 'e']])
print(b)

[['x' 'y' 'z']
 ['a' 'c' 'e']]


In [22]:
# Dimension del arreglo
b.ndim

2

In [23]:
# Metodo de ordenamiento
c = [15,2,60,10,5,1]
np.sort(c)

array([ 1,  2,  5, 10, 15, 60])

In [32]:
cabeceras = [('nombre', 'S10'), ('edad', int), ('pais', 'S20')]
datos = [('Juan', 10, 'Mexico'), ('Maria', 70, 'Canada'), ('Javier', 42, 'EUA'), ('Samuel', 15, 'Colombia')]
usuarios = np.array(datos, dtype=cabeceras)

np.sort(usuarios, order='edad')

array([(b'Juan', 10, b'Mexico'), (b'Samuel', 15, b'Colombia'),
       (b'Javier', 42, b'EUA'), (b'Maria', 70, b'Canada')],
      dtype=[('nombre', 'S10'), ('edad', '<i4'), ('pais', 'S20')])

In [26]:
# Llenar arrays de manera dinamica
print('Limite: 20')
print(np.arange(20))
print('Primer valor: 5, Limite: 25')
print(np.arange(5,25))
print('Primer valor: 5, Limite: 50, Saltos: 5')
print(np.arange(5,50,5))

Limite: 20
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Primer valor: 5, Limite: 25
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Primer valor: 5, Limite: 50, Saltos: 5
[ 5 10 15 20 25 30 35 40 45]


In [29]:
# Crear arreglos bidimensionales
np.full((3,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [30]:
# Crear diagonal
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])